# app/main.py
from typing import List, Optional, Dict, Any, Set, Tuple
import os, json, re, unicodedata
from difflib import SequenceMatcher, get_close_matches

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# RAG / training
from .rag import retrieve, generate_answer, detect_gen, extract_found_gens
from .ingest import ingest_path
from .training import add_correction, search_correction, save_feedback
from .config import CORRECTION_THRESHOLD, STORE_DIR

app = FastAPI(title="Chatbot Piscines API")

# ---------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------
ALLOWED_ORIGINS = [
    "https://beniferro.eu",
    "https://www.beniferro.eu",
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=[
        "Content-Type",
        "ngrok-skip-browser-warning",
        "Authorization",
        "Accept",
        "Origin",
    ],
    expose_headers=["Content-Type"],
)

# ---------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------
class ChatRequest(BaseModel):
    query: str
    audience: str = "client"
    debug: bool = False
    extra: Optional[Dict[str, Any]] = None  # e.g. {"clarify_ref": "...", "gen":"gen1"}

class IngestRequest(BaseModel):
    path: str
    source_type: str = "mixed"

class CorrectionIn(BaseModel):
    question: str
    answer: str
    tags: List[str] = []

class FeedbackIn(BaseModel):
    question: str
    answer: str
    good: bool
    corrected_answer: Optional[str] = None
    notes: Optional[str] = None
    user: Optional[str] = None

# ---------------------------------------------------------------------
# Constants / Tips
# ---------------------------------------------------------------------
GEN_TIPS_NL = [
    "1) Een Gen 2 apparaat heeft een ethernet (internetkabel) aansluiting.",
    "2) Bij ‘toestellen zoeken’: Gen 1 toont meestal meerdere modules; Gen 2 meestal maar 1 module.",
    "3) Gen 1 heeft vaak een USB 5V stekker; Gen 2 heeft 220V of 12V stekker.",
]

# ---------------------------------------------------------------------
# Load FAQ (JSON generated by /ingest)
# ---------------------------------------------------------------------
_FAQ_PATH = os.path.join(STORE_DIR, "faq_index.json")
_FAQ: List[dict] = []

def _reload_faq() -> Tuple[int, List[dict]]:
    """Reload index from disk; returns (count, data)."""
    data: List[dict] = []
    try:
        with open(_FAQ_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        data = []
    global _FAQ
    _FAQ = data
    return (len(_FAQ), _FAQ)

# Load once at startup
_reload_faq()

# ---------------------------------------------------------------------
# Normalization & matching helpers
# ---------------------------------------------------------------------
_PUNCT_RE = re.compile(r"\s*[?!.:,;()\-\[\]«»“”\"'`]\s*")

def _normalize(s: str | None) -> str:
    s = unicodedata.normalize("NFKD", (s or ""))
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.replace("\u00a0", " ").lower()
    s = re.sub(r"\s+", " ", s)
    s = _PUNCT_RE.sub("", s)
    return s.strip()

def _ratio(a: str, b: str) -> float:
    return SequenceMatcher(None, a, b).ratio()

def _looks_like_followup_choice(text: str) -> bool:
    t = _normalize(text)
    return t in {
        "gen1","gen 1","g1",
        "gen2","gen 2","g2",
        "gen3","gen 3","g3",
        "wifipool","wifi","wifi apparaat","wifi-apparaat",
        "benisol","zonder wifi","display","display apparaat","display-apparaat"
    }

# fuzzy match question
def _find_row_by_question(user_q: str) -> dict | None:
    if not _FAQ:
        return None
    uq = _normalize(user_q)

    # 1) Exact / inclusion
    for row in _FAQ:
        q = _normalize(row.get("question", ""))
        if q and (uq == q or uq in q or q in uq):
            return row

    # 2) Fuzzy best
    best = (0.0, None)
    for row in _FAQ:
        q = _normalize(row.get("question", ""))
        if not q:
            continue
        sc = _ratio(uq, q)
        if sc > best[0]:
            best = (sc, row)
    return best[1] if best[0] >= 0.80 else None

def _find_row_by_ref(ref_q: str) -> dict | None:
    """Find row by clarify_ref/context_question coming from the client."""
    if not ref_q:
        return None
    uq = _normalize(ref_q)
    best = (0.0, None)
    for row in _FAQ:
        q = _normalize(row.get("question", ""))
        if not q:
            continue
        if uq == q or uq in q or q in uq:
            return row
        sc = _ratio(uq, q)
        if sc > best[0]:
            best = (sc, row)
    return best[1] if best[0] >= 0.75 else None

# ---------------------------------------------------------------------
# Options / GEN helpers
# ---------------------------------------------------------------------
_GEN_ALIASES: Dict[str, set] = {
    "gen1": {"gen1", "gen 1", "g1", "generation 1"},
    "gen2": {"gen2", "gen 2", "g2", "generation 2"},
    "gen3": {"gen3", "gen 3", "g3", "generation 3"},
}
_DEVICE_ALIASES: Dict[str, set] = {
    "wifipool": {"wifipool", "wifi", "wifi apparaat", "wifi-apparaat"},
    "benisol": {"benisol", "zonder wifi"},
    "display": {"display", "display apparaat", "display-apparaat"},
}

def _map_choice_to_key(choice: str, option_labels: List[str]) -> str | None:
    """Map a user choice ('gen 1', 'wifipool', 'display', …) to one of the option labels."""
    t = _normalize(choice)
    # 1) direct alias resolution
    for key, al in _GEN_ALIASES.items():
        if t in al:
            # match against option labels containing gen1/gen 1 …
            for lbl in option_labels:
                if "gen" in _normalize(lbl) and ("1" in lbl or "2" in lbl or "3" in lbl):
                    # pick best with fuzzy
                    pass
            # fall through to fuzzy below
            break
    for key, al in _DEVICE_ALIASES.items():
        if t in al:
            # find closest option label containing that key text
            candidates = [lbl for lbl in option_labels if key in _normalize(lbl)]
            if candidates:
                return candidates[0]

    # 2) fuzzy over labels
    matches = get_close_matches(choice, option_labels, n=1, cutoff=0.6)
    if matches:
        return matches[0]

    # 3) fallback: try normalized contains
    for lbl in option_labels:
        if _normalize(lbl) in t or t in _normalize(lbl):
            return lbl
    return None

def _is_ask_gen(row: dict) -> bool:
    if row.get("ask_gen") is True:
        return True
    # heuristique : des options libellées Gen 1 / Gen 2
    opts = row.get("options") or {}
    return any("gen" in _normalize(k) for k in opts.keys())

def _labels(row: dict) -> List[str]:
    opts = row.get("options") or {}
    return list(opts.keys())

def _render_option_payload(payload: Any) -> str:
    """
    Transforme la valeur d'une option (souvent un dict) en texte.
    - si 'answer'/'antwoord' présent -> renvoie ça + recommandation si dispo
    - sinon, rend les champs clés sous forme de puces
    """
    if not isinstance(payload, dict):
        return str(payload)

    ans = (payload.get("answer") or payload.get("antwoord") or "").strip()
    rec = (payload.get("recommendation") or payload.get("aanbeveling") or "").strip()
    if ans:
        if rec:
            return ans + ("\n\nAanbeveling: " + rec)
        return ans

    # Pas de 'answer': on déroule proprement
    lines: List[str] = []
    for k, v in payload.items():
        if v in (None, "", []):
            continue
        key = str(k).replace("_", " ").strip().capitalize()
        if isinstance(v, list):
            items = "\n".join([f"  • {str(x)}" for x in v if str(x).strip()])
            lines.append(f"{key}:\n{items}")
        elif isinstance(v, dict):
            # on a un sous-dict : on aplatit simple
            items = []
            for kk, vv in v.items():
                if vv in (None, "", []): continue
                items.append(f"{kk}: {vv}")
            if items:
                lines.append(f"{key}: " + "; ".join(items))
        else:
            lines.append(f"{key}: {v}")
    return "\n".join(lines).strip()

def _build_answer_for_option(row: dict, option_label: str) -> str:
    """Construit la réponse finale pour une option choisie."""
    opts = row.get("options") or {}
    payload = opts.get(option_label)
    if payload is None:
        # rien trouvé -> message propre
        return "Ik heb geen details gevonden voor deze keuze."
    intro = (row.get("answer") or row.get("antwoord") or "").strip()
    body = _render_option_payload(payload)
    return (intro + "\n\n" + body).strip() if intro else body

def _choose_gen_answer(row: dict, gen_key: str) -> str | None:
    """Si la ligne possède answer_gen1/2/3, on renvoie; sinon None."""
    if gen_key == "gen1" and row.get("answer_gen1"):
        return str(row["answer_gen1"]).strip()
    if gen_key == "gen2" and row.get("answer_gen2"):
        return str(row["answer_gen2"]).strip()
    if gen_key == "gen3" and row.get("answer_gen3"):
        return str(row["answer_gen3"]).strip()
    return None

def _map_choice_to_genkey(choice: str) -> str | None:
    t = _normalize(choice)
    for key, al in _GEN_ALIASES.items():
        if t in al:
            return key
    return None

# ---------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------
@app.get("/health")
def health():
    return {"status": "ok", "faq_rows": len(_FAQ)}

@app.get("/debug/faq_lookup")
def dbg_lookup(q: str):
    row = _find_row_by_question(q)
    return {"q": q, "found": bool(row), "row": row}

@app.post("/ingest")
def ingest(req: IngestRequest):
    res = ingest_path(req.path, req.source_type)
    # recharger l'index si régénéré
    _reload_faq()
    return {"reloaded": True, "faq_rows": len(_FAQ), **res}

@app.post("/train/correction")
def train_correction(req: CorrectionIn):
    return add_correction(req.question, req.answer, req.tags)

@app.post("/feedback")
def feedback(req: FeedbackIn):
    return save_feedback(req.dict())

# ---------------------------------------------------------------------
# Chat core
# ---------------------------------------------------------------------
def _citations_for_row(row: dict) -> List[dict]:
    return [{
        "title": row.get("question") or "FAQ",
        "source": row.get("source") or "",
        "page": None
    }]

def _parse_extra_gen(extra: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(extra, dict): return None
    g = str(extra.get("gen", "")).strip().lower()
    if g in {"gen1", "gen 1"}: return "gen1"
    if g in {"gen2", "gen 2"}: return "gen2"
    if g in {"gen3", "gen 3"}: return "gen3"
    return None

@app.post("/chat")
def chat(req: ChatRequest):
    q = (req.query or "").strip()
    extra = req.extra or {}
    clarify_ref = (extra.get("clarify_ref") or extra.get("context_question") or "") and str(extra.get("clarify_ref") or extra.get("context_question"))
    clarify_ref = clarify_ref.strip()

    # 0) Corrections admin (surclassent tout)
    ans, cite, score = search_correction(q, k=1, threshold=CORRECTION_THRESHOLD)
    if ans:
        used = [] if not req.debug else [{"meta": {"source_type": "correction", "score": score}, "text": ""}]
        return {"answer": ans, "citations": [cite], "used_chunks": used}

    # 1) Si on reçoit une réponse à une follow-up (clarify_ref/context_question renseigné)
    if clarify_ref:
        base_row = _find_row_by_ref(clarify_ref)
        if not base_row:
            # si le front a oublié la ref -> message clair
            return {
                "answer": "Ik kan je keuze niet aan de juiste vraag koppelen. Kies opnieuw bij de vorige vraag of geef de contextvraag mee.",
                "citations": []
            }

        # cas GEN direct via answer_gen*
        gen_key = _map_choice_to_genkey(q)
        if gen_key:
            chosen = _choose_gen_answer(base_row, gen_key)
            if chosen:
                return {"answer": chosen, "citations": _citations_for_row(base_row)}

        # sinon, appariement d'une option
        labels = _labels(base_row)
        if not labels:
            # rien à choisir → on renvoie la réponse directe s'il y en a
            direct = (base_row.get("answer") or base_row.get("antwoord") or "").strip()
            if direct:
                return {"answer": direct, "citations": _citations_for_row(base_row)}
            return {"answer": "Geen antwoord gevonden.", "citations": []}

        label = _map_choice_to_key(q, labels)
        if not label:
            return {
                "answer": "Ik herken deze keuze niet. Kies één van: " + ", ".join(labels),
                "citations": _citations_for_row(base_row)
            }
        answer = _build_answer_for_option(base_row, label)
        return {"answer": answer, "citations": _citations_for_row(base_row)}

    # 1b) Si on reçoit une “réponse nue” (Gen 1 / Wifipool / …) sans ref
    if _looks_like_followup_choice(q):
        return {
            "answer": "Ik heb nog even de context nodig: bij welke vraag hoort deze keuze? Kies opnieuw bij de vorige vraag, of stuur je keuze met de contextvraag mee.",
            "need_ref": True,
            "citations": []
        }

    # 2) Lookup direct dans l'index FAQ (JSON/JSONL)
    row = _find_row_by_question(q)
    if row:
        # follow-up demandé ?
        if row.get("follow_up"):
            labels = _labels(row)
            tips: List[str] = GEN_TIPS_NL if _is_ask_gen(row) else []
            return {
                "answer": row.get("followup_q") or row.get("follow_up_question") or "Kunt u een keuze maken?",
                "clarify": {
                    "ref": row.get("question"),
                    "options": labels,
                    "tips": tips
                },
                "citations": _citations_for_row(row)
            }

        # réponse directe
        direct = (row.get("answer") or row.get("antwoord") or "").strip()
        if direct:
            extra_line = ""
            if row.get("video_url"):
                extra_line = "\n\nBekijk video: " + str(row["video_url"])
            return {"answer": direct + extra_line, "citations": _citations_for_row(row)}

    # 3) Sinon → pipeline RAG classique
    extra_gen = _parse_extra_gen(req.extra)
    try:
        gen = extra_gen or detect_gen(q)
    except Exception:
        gen = extra_gen

    try:
        docs = retrieve(q, gen_filter=gen)
    except TypeError:
        docs = retrieve(q)

    try:
        found: Set[str] = extract_found_gens(docs)
    except Exception:
        found = set()

    if not gen and found:
        options = sorted(list(found & {"gen1", "gen2", "gen3"})) or ["gen1", "gen2"]
        return {
            "answer": "Hebt u een Gen 1 of een Gen 2 apparaat?",
            "clarify": {"ref": q, "options": options, "tips": GEN_TIPS_NL},
            "citations": [],
        }

    if not docs:
        return {
            "answer": "Het lijkt erop dat er geen specifieke context beschikbaar is om je vraag te beantwoorden. Kun je meer details geven over wat je precies wilt weten?",
            "citations": [],
        }

    answer, citations = generate_answer(q, docs)
    return {"answer": answer, "citations": citations}
